# Basic Settings
title: Plant-T
url: "https://vertical-farming-ib3.github.io"
baseurl: ""
lang: nl
timezone: Europe/Brussels
theme: minima

# Site Metadata
description: "Bachelorproefproject over verticale landbouw door elektronica studenten KU Leuven Gent"
tagline: "Bachelorproef '24-'25"

# Author/Social
author:
  name: "Elektronica studenten KU Leuven Gent"
  email: "beau.forrez@student.kuleuven.be"
  
social:
  github:
    username: "Vertical-Farming-IB3"
    repo: "Plan-T"

# Avatar (make sure this file exists in your repo)
avatar: "assets/img/favicons/web-app-manifest-512x512.png"

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - "*.gem"
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - package.json
  - package-lock.json
  - node_modules